<<<<<<< HEAD

-- 문제용 테이블 CREATE

CREATE TABLE EMPP
(EMPNO      CHAR(4) NOT NULL ENABLE, 
	ENAME      VARCHAR2(20) NOT NULL ENABLE, 
	JOB        VARCHAR2(30) NOT NULL ENABLE, 
	MGR        VARCHAR2(4), 
	HIREDATE   DATE NOT NULL ENABLE, 
	SAL        NUMBER(10,0) NOT NULL ENABLE, 
	COMM       NUMBER, 
	DEPTNO     VARCHAR2(2) NOT NULL ENABLE,
CONSTRAINT XPK_EMP PRIMARY KEY (EMPNO) );

CREATE TABLE DEPT
(DEPTNO     CHAR(2) NOT NULL ENABLE,
	DNAME      VARCHAR2(20) NOT NULL ENABLE, 
	LOC        VARCHAR2(30) NOT NULL ENABLE,
CONSTRAINT XPK_DEPT PRIMARY KEY (DEPTNO) );

-- 사원관리
INSERT INTO EMPP(EMPNO,  ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7369', '장길동', '프로그래머', '7902', '2013/12/17', 600, 200 , '50');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7499', '고영우', '시장조사', '7698', '2021/02/20', 550, 300 , '20');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7521', '구기현', '영업사원', '7698', '2020/02/22', 250, 400 , '30');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7566', '김동혁', '관리자', '7839', '2012/04/02', 375,NULL, '40');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7654', '김민욱', '영업사원', '7698', '2018/09/28', 350, 700 , '30');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7698', '김민정', '관리자', '7839', '2014/05/01', 450,NULL, '40');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7782', '김지완', '관리자', '7839', '2022/02/20', 470, 600, '40');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7788', '박승우', '분석가', '7839', '2021/03/22', 300,NULL , '50');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7839', '박윤수', '대표이사', NULL, '2010/01/05', 900, 100, '40');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7844', '박정수', '영업사원', '7698', '2016/09/28',340,NULL, '30');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7876', '배문기', '회계업무', '7788', '2014/05/01', 420,NULL, '10');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7900', '변정민', '시장분석', '7698', '2012/04/02', 750,NULL, '20');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7902', '신국현', '분석가', '7566', '2019/09/28', 300,NULL, '50');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7934', '신현근', '프로그래머', '7782', '2018/01/23', 290,400, '50');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7999', '오대환', '회계업무', '7782',SYSDATE, 210,NULL, '10');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('8000', '정범진', '프로그래머', '7839',SYSDATE, 6500,NULL, '50');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7997', '김민수', '프로그래머', '7839',SYSDATE, 6500,NULL, '30');

UPDATE EMPP SET DEPTNO='40' WHERE ENAME = '김민수';

SELECT * FROM EMPP ORDER BY EMPNO ASC;

-- 부서관리
INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES('10', '회계부', '서울');
INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES('20', '조사부', '세종');
INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES('30', '영업부', '서울');
INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES('40', '관리부', '대전');
INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES('50', '개발부', '대전');

delete from empp;
delete from dept;



SELECT ENAME 사원명, SAL 급여, SAL+300 인상된급여 FROM EMPP ORDER BY SAL DESC;
SELECT ENAME 사원명, SAL 급여, SAL*0.05 "월급의 5%" ,ROUND(SAL*1.05,0) "5%로 인상된급여" 
        FROM EMPP ORDER BY SAL DESC;

UPDATE EMPP SET JOB='프로그래머' WHERE EMPNO = '7999';

ALTER TABLE EMPP MODIFY (JOB VARCHAR2(20));

ALTER TABLE EMPP MODIFY (DEPTNO CHAR(2));
ALTER TABLE DEPT MODIFY (DEPTNO CHAR(2));
ALTER TABLE EMPP ADD(CONSTRAINT XFK_EMP FOREIGN KEY (DEPTNO) REFERENCES DEPT(DEPTNO));

UPDATE EMPP SET SAL=ROUND(SAL*0.5,0) WHERE SAL = ''  ;
SELECT ENAME 사원명, SAL 급여, SAL*12+100 "연간 총 수입" 
        FROM EMPP ORDER BY "연간 총 수입" ASC;

SELECT ENAME 사원명, SAL 급여 FROM EMPP WHERE SAL>'500' ORDER BY SAL DESC;

SELECT ENAME 사원명, DEPTNO 부서번호 FROM EMPP WHERE MGR='7788';

SELECT ENAME 사원명, SAL 급여 FROM EMPP WHERE NOT SAL BETWEEN 400 AND 800 ORDER BY SAL ASC; 
SELECT ENAME 사원명, SAL 급여 FROM EMPP WHERE SAL < 400 OR SAL > 800 ORDER BY SAL ASC;

UPDATE EMPP SET HIREDATE = TO_DATE('20'||SUBSTR(hiredate,1), 'YYYY/MM/DD');
SELECT ENAME 사원명, JOB 담당업무, HIREDATE 입사일 
        FROM EMPP WHERE HIREDATE BETWEEN '1981/02/20' AND '2018/05/01' ORDER BY hiredate ASC;
        
SELECT ENAME 사원명, DEPTNO 부서번호 
        FROM EMPP WHERE DEPTNO BETWEEN 20 AND 30 ORDER BY ENAME DESC;

























=======

-- 문제용 테이블 CREATE

CREATE TABLE EMPP
(EMPNO      CHAR(4) NOT NULL ENABLE, 
	ENAME      VARCHAR2(20) NOT NULL ENABLE, 
	JOB        VARCHAR2(30) NOT NULL ENABLE, 
	MGR        VARCHAR2(4), 
	HIREDATE   DATE NOT NULL ENABLE, 
	SAL        NUMBER(10,0) NOT NULL ENABLE, 
	COMM       NUMBER, 
	DEPTNO     VARCHAR2(2) NOT NULL ENABLE,
CONSTRAINT XPK_EMP PRIMARY KEY (EMPNO) );

CREATE TABLE DEPT
(DEPTNO     CHAR(2) NOT NULL ENABLE,
	DNAME      VARCHAR2(20) NOT NULL ENABLE, 
	LOC        VARCHAR2(30) NOT NULL ENABLE,
CONSTRAINT XPK_DEPT PRIMARY KEY (DEPTNO) );

-- 사원관리
INSERT INTO EMPP(EMPNO,  ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7369', '장길동', '프로그래머', '7902', '2013/12/17', 600, 200 , '50');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7499', '고영우', '시장조사', '7698', '2021/02/20', 550, 300 , '20');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7521', '구기현', '영업사원', '7698', '2020/02/22', 250, 400 , '30');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7566', '김동혁', '관리자', '7839', '2012/04/02', 375,NULL, '40');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7654', '김민욱', '영업사원', '7698', '2018/09/28', 350, 700 , '30');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7698', '김민정', '관리자', '7839', '2014/05/01', 450,NULL, '40');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7782', '김지완', '관리자', '7839', '2022/02/20', 470, 600, '40');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7788', '박승우', '분석가', '7839', '2021/03/22', 300,NULL , '50');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7839', '박윤수', '대표이사', NULL, '2010/01/05', 900, 100, '40');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7844', '박정수', '영업사원', '7698', '2016/09/28',340,NULL, '30');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7876', '배문기', '회계업무', '7788', '2014/05/01', 420,NULL, '10');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7900', '변정민', '시장분석', '7698', '2012/04/02', 750,NULL, '20');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7902', '신국현', '분석가', '7566', '2019/09/28', 300,NULL, '50');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7934', '신현근', '프로그래머', '7782', '2018/01/23', 290,400, '50');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7999', '오대환', '회계업무', '7782',SYSDATE, 210,NULL, '10');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('8000', '정범진', '프로그래머', '7839',SYSDATE, 6500,NULL, '50');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7997', '김민수', '프로그래머', '7839',SYSDATE, 6500,NULL, '30');

UPDATE EMPP SET DEPTNO='40' WHERE ENAME = '김민수';

SELECT * FROM EMPP ORDER BY EMPNO ASC;

-- 부서관리
INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES('10', '회계부', '서울');
INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES('20', '조사부', '세종');
INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES('30', '영업부', '서울');
INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES('40', '관리부', '대전');
INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES('50', '개발부', '대전');

delete from empp;
delete from dept;



SELECT ENAME 사원명, SAL 급여, SAL+300 인상된급여 FROM EMPP ORDER BY SAL DESC;
SELECT ENAME 사원명, SAL 급여, SAL*0.05 "월급의 5%" ,ROUND(SAL*1.05,0) "5%로 인상된급여" 
        FROM EMPP ORDER BY SAL DESC;

UPDATE EMPP SET JOB='프로그래머' WHERE EMPNO = '7999';

ALTER TABLE EMPP MODIFY (JOB VARCHAR2(20));

ALTER TABLE EMPP MODIFY (DEPTNO CHAR(2));
ALTER TABLE DEPT MODIFY (DEPTNO CHAR(2));
ALTER TABLE EMPP ADD(CONSTRAINT XFK_EMP FOREIGN KEY (DEPTNO) REFERENCES DEPT(DEPTNO));

UPDATE EMPP SET SAL=ROUND(SAL*0.5,0) WHERE SAL = ''  ;
SELECT ENAME 사원명, SAL 급여, SAL*12+100 "연간 총 수입" 
        FROM EMPP ORDER BY "연간 총 수입" ASC;

SELECT ENAME 사원명, SAL 급여 FROM EMPP WHERE SAL>'500' ORDER BY SAL DESC;

SELECT ENAME 사원명, DEPTNO 부서번호 FROM EMPP WHERE MGR='7788';

SELECT ENAME 사원명, SAL 급여 FROM EMPP WHERE NOT SAL BETWEEN 400 AND 800 ORDER BY SAL ASC; 
SELECT ENAME 사원명, SAL 급여 FROM EMPP WHERE SAL < 400 OR SAL > 800 ORDER BY SAL ASC;

UPDATE EMPP SET HIREDATE = TO_DATE('20'||SUBSTR(hiredate,1), 'YYYY/MM/DD');
SELECT ENAME 사원명, JOB 담당업무, HIREDATE 입사일 
        FROM EMPP WHERE HIREDATE BETWEEN '1981/02/20' AND '2018/05/01' ORDER BY hiredate ASC;
        
SELECT ENAME 사원명, DEPTNO 부서번호 
        FROM EMPP WHERE DEPTNO BETWEEN 20 AND 30 ORDER BY ENAME DESC;

























>>>>>>> origin/main
