<<<<<<< HEAD


INSERT INTO EMPLOYEE(E_ENP_NO,E_NAME,E_ADDRESS,E_TEL_NO,E_POSITION,e_department)
    VALUES('A001','김민수','대전시 둔산로 1001번길','010-1234-5678','사원','영업부');
INSERT INTO EMPLOYEE(E_ENP_NO,E_NAME,E_ADDRESS,E_TEL_NO,E_POSITION,e_department)
    VALUES('A002','박대기','대전시 둔산로 1002번길','010-1234-2368','대리','영업부');
INSERT INTO EMPLOYEE(E_ENP_NO,E_NAME,E_ADDRESS,E_TEL_NO,E_POSITION,e_department)
    VALUES('A003','양찬세','대전시 산수로 1012번길','010-5234-3668','사원','사업부');
INSERT INTO EMPLOYEE(E_ENP_NO,E_NAME,E_ADDRESS,E_TEL_NO,E_POSITION,e_department)
    VALUES('A004','이길찬','대전시 로 1002번길','010-1234-2368','대리','영업부');

INSERT INTO SITE(S_SITE_NO,S_SITE_NAME,S_SDATE,S_INSERT_QTY,S_EXP_EDATE,S_EDATE,S_PRICE,S_ADDRESS,S_TEL_NO,S_REMARK)
=======


INSERT INTO EMPLOYEE(E_ENP_NO,E_NAME,E_ADDRESS,E_TEL_NO,E_POSITION,e_department)
    VALUES('A001','김민수','대전시 둔산로 1001번길','010-1234-5678','사원','영업부');
INSERT INTO EMPLOYEE(E_ENP_NO,E_NAME,E_ADDRESS,E_TEL_NO,E_POSITION,e_department)
    VALUES('A002','박대기','대전시 둔산로 1002번길','010-1234-2368','대리','영업부');
INSERT INTO EMPLOYEE(E_ENP_NO,E_NAME,E_ADDRESS,E_TEL_NO,E_POSITION,e_department)
    VALUES('A003','양찬세','대전시 산수로 1012번길','010-5234-3668','사원','사업부');
INSERT INTO EMPLOYEE(E_ENP_NO,E_NAME,E_ADDRESS,E_TEL_NO,E_POSITION,e_department)
    VALUES('A004','이길찬','대전시 로 1002번길','010-1234-2368','대리','영업부');

INSERT INTO SITE(S_SITE_NO,S_SITE_NAME,S_SDATE,S_INSERT_QTY,S_EXP_EDATE,S_EDATE,S_PRICE,S_ADDRESS,S_TEL_NO,S_REMARK)
>>>>>>> origin/main
    VALUES('');