
DROP TABLE EMPOLYER;                     -- 테이블 삭제

CREATE TABLE EMPOLYER(                  -- 테이블 생성
    EMPNO CHAR(6) NOT NULL,            -- 부서 번호
    ENAME  VARCHAR2(20) NOT NULL,  -- 이름
    DEPT     VARCHAR2(16) NOT NULL,  -- 부서명
    TEL       VARCHAR2(14),                  -- 전화번호
    SALARY NUMBER(10),                      -- 급여
    CONSTRAINT PK_EMPNO PRIMARY KEY (EMPNO)      -- 프라이머리 키 생성
);
ALTER TABLE EMPOLYER ADD (ADDRESS VARCHAR2 (50) NOT NULL);  -- 필드 생성
ALTER TABLE EMPOLYER MODIFY(DEPT VARCHAR2(30));                     -- 필드 속성 변경

CREATE TABLE EMPOLYER(                  -- 테이블 생성
    EMPNO CHAR(6) NOT NULL,            -- 부서 번호
    ENAME  VARCHAR2(20) NOT NULL,  -- 이름
    ADDRESS VARCHAR2 (50) NOT NULL, -- 주소
    DEPT     VARCHAR2(16) NOT NULL,  -- 부서명
    TEL       VARCHAR2(14),                  -- 전화번호
    SALARY NUMBER(10),                      -- 급여
    CONSTRAINT PK_EMPNO PRIMARY KEY (EMPNO)      -- 프라이머리 키 생성
);


INSERT INTO EMPOLYER(EMPNO, ENAME, DEPT, TEL, SALARY, ADDRESS)
    VALUES('100','김기훈','영업부','010-8422-8117',300,'대전광역시 서구 둔산로31번길 31');
INSERT INTO EMPOLYER(EMPNO,ENAME,DEPT,TEL,SALARY,ADDRESS)
        VALUES('101','홍성범','기획부','010-7562-3217',350,'대전광역시 서구 계룡로29번길 50');
 INSERT INTO EMPOLYER(EMPNO,ENAME,DEPT,TEL,SALARY,ADDRESS)
        VALUES('102','이만수','기획부','010-5562-6677',500,'대전광역시 중구 대사로30번길 10');
 INSERT INTO EMPOLYER(EMPNO,ENAME,DEPT,TEL,SALARY,ADDRESS)
        VALUES('103','강나미','영업부','010-4442-5614',350,'대전광역시 중구 선화로10번길 30');
 INSERT INTO EMPOLYER(EMPNO,ENAME,DEPT,TEL,SALARY,ADDRESS)
        VALUES('109','민병철','총무부','010-2542-8211',250,'대전광역시 동구 산내로1205번길 24');

INSERT INTO EMPOLYER(EMPNO,ENAME,DEPT,TEL,SALARY,ADDRESS)
        VALUES('110','정범진','개발부','010-9303-1907',250,'대전광역시 서구 동서대로1014번길 25');

SELECT * FROM EMPOLYER;             -- 데이터 조회

-- 간단한 SQL 문장 테스트 하기
-- 사원번호가 110인 사원 조회
SELECT * FROM EMPOLYER WHERE EMPNO='110';
-- 급여가 250만원인 사원 조회
SELECT * FROM EMPOLYER WHERE SALARY=250;
-- 현재 사원수 조회
SELECT COUNT(*) 총사원수 FROM EMPOLYER;
-- 급여가 300만원 이상인 사원 조회
SELECT * FROM EMPOLYER WHERE SALARY>=300;



-- 테이블 및 데이터 생성 SQL Developer
DROP TABLE EMP;

CREATE TABLE EMP(
    EMPID   CHAR(6) NOT NULL,
    SUNG    VARCHAR2(20) NOT NULL,
    DEPT    VARCHAR2(20) NOT NULL,
    HIRE_DATE   DATE,
    BIRTHDAY    VARCHAR2(20),
    ADDRESS VARCHAR2(50),
    JOB     VARCHAR2(20),
    SALARY     NUMBER(10),
    CONSTRAINT PK_EMP PRIMARY KEY(EMPID)
);

 INSERT INTO EMP(EMPID,SUNG,DEPT,HIRE_DATE,BIRTHDAY, ADDRESS, JOB, SALARY)
        VALUES('1006','장승수','개발부',SYSDATE,'1985.10.12','대전 서구 내동 345', 'ERP프로그램', 350);
   INSERT INTO EMP(EMPID,SUNG,DEPT,HIRE_DATE,BIRTHDAY, ADDRESS, JOB, SALARY)
        VALUES('1002','곽희준','영업부',SYSDATE,'1985.10.12','안양 용봉동', '특수영업', 400);
   INSERT INTO EMP(EMPID,SUNG,DEPT,HIRE_DATE,BIRTHDAY, ADDRESS, JOB, SALARY)
        VALUES('1003','김동준','생산부',SYSDATE,'1985.10.12','부산 대하동', '품질관리', 300);
   INSERT INTO EMP(EMPID,SUNG,DEPT,HIRE_DATE,BIRTHDAY, ADDRESS, JOB, SALARY)
        VALUES('1004','성재규','인사부',SYSDATE,'1985.10.12','대구 달성동', '급여관리', 450);
   INSERT INTO EMP(EMPID,SUNG,DEPT,HIRE_DATE,BIRTHDAY, ADDRESS, JOB, SALARY)
        VALUES('1005','박성범','구매부',SYSDATE,'1985.10.12','대전 요류동', '수입자재', 320);

SELECT * FROM EMP;

CREATE VIEW VIEW_EMP1 AS SELECT EMPID, SUNG, DEPT, HIRE_DATE, SALARY FROM EMP;
-- WHERE SALARY >= 150;
CREATE VIEW VIEW_EMP2 AS SELECT EMPID, SUNG, DEPT, JOB FROM EMP;
CREATE VIEW VIEW_EMP3 AS SELECT EMPID, SUNG, BIRTHDAY, ADDRESS FROM EMP;

SELECT * FROM view_emp1;
SELECT * FROM view_emp2;
SELECT * FROM view_emp3;

-- VIEW에서 간단한 SQL 문장 테스트 하기
-- VIEW_EMP1에서 고용일이 2000년 이후이고 급여가 350만원 이상인 사원 조회
SELECT * FROM VIEW_EMP1 WHERE SUBSTR(HIRE_DATE, 1, 4) > '2000' AND SALARY>=350;
-- VIEW_EMP2에서 업무(JOB)가 특수영업인 사원 조회
SELECT * FROM VIEW_EMP2 WHERE JOB = '특수영업';
-- VIEW_EMP3에서 생일이 1986년도인 사원 조회
SELECT * FROM VIEW_EMP3 WHERE SUBSTR(BIRTHDAY, 1, 4) = '1985';










