SELECT '<' || LTRIM('       AAA      ') || '>' LTRIM1, '<' 
    || LTRIM('HELOOW WORLD', 'HE') || '>' LTRIM2 FROM DUAL;
SELECT '<' || RTRIM('       AAA      ') || '>' RTRIM1, '<' 
    || RTRIM('HELOOW WORLD', 'LD') || '>' RTRIM2 FROM DUAL;

SELECT '<' || TRIM('     A A A     ') || '>' TRIM1,
    '<' || TRIM(LEADING 'a' FROM 'aaAaBaAaa') || '>' TRIM2,
    '<' || TRIM(TRAILING 'a' FROM 'aaAaBaAaa') || '>' TRIM3,
    '<' || TRIM(BOTH 'a'  FROM 'aaAaBaAaa') || '>' TRIM4,
    '<' || TRIM( 'a' FROM 'aaAaBaAaa') || '>' TRIM5
    FROM DUAL;
    
-- DUAL 더미 테이블
SELECT * FROM DUAL;

-- SUBSTR [문자열] [시작위치] [범위]
SELECT SUBSTR('SQL PROJECT', 1, 3) RESULT1,
        SUBSTR('SQL PROJECT', 5) RESULT2,
        SUBSTR('SQL PROJECT', -7, 3) RESULT3,
        SUBSTR('SQL PROJECT', 3, 5) RESULT4,
        SUBSTR('SQL PROJECT', -4, 2) RESULT5
        FROM DUAL;
        
SELECT MEM_ID, SUBSTR(MEM_NAME, 1, 1) 성씨 FROM MEMBER;

SELECT PROD_ID 상품코드, PROD_NAME 칼라상품명 
        FROM PROD WHERE SUBSTR(PROD_NAME, 4, 2) = '칼라';

SELECT REPLACE('SQL Project', 'SQL', 'SSQQLL') 문자치환1, REPLACE('Java Flex Via', 'a')
        FROM DUAL;
SELECT MEM_NAME 회원명, 
        REPLACE(SUBSTR(MEM_NAME, 1, 1), '이', '리') || SUBSTR(MEM_NAME, 2, 2) 치환회원명
        FROM MEMBER WHERE SUBSTR(MEM_NAME, 1, 1) = '이';

-- TRANSLATE [대상 문자열] [치환할 문자] [치환될 문자](부족하면 삭제]
SELECT TRANSLATE('2009-02-28', '0123456789-', '영일이삼사오육칠팔구/') RESULT
        FROM DUAL;
SELECT MEM_ID 회원아이디, TRANSLATE(MEM_ID, '0123456789', ' ') 변환아이디
        FROM MEMBER;

-- INSTR [검색할 문자열] [찾을 문자열] [시작 위치] [N번째 위치(기본값 1)]
SELECT INSTR('HELLO HEIDI', 'HE') RESULT1, INSTR('HELLO HEIDI', 'HE', 3) RESULT2
        FROM DUAL;

SELECT LENGTH('SQL 프로젝트') LENGTH, LENGTHB('SQL 프로젝트') LENGTHB 
        FROM DUAL;

SELECT  ABS(-365) FROM DUAL;
SELECT SIGN(12),  SIGN(0),  SIGN(-55)
        FROM DUAL;
SELECT  POWER(3, 2) ,    POWER(2, 10)  
        FROM DUAL;
SELECT  SQRT(2) , SQRT(9) FROM DUAL;

SELECT ROUND(345.123, 0) 결과 FROM DUAL;
SELECT ROUND(345.123, -1) 결과1, TRUNC(345.123, -1) 결과2 FROM DUAL;

SELECT * FROM MEMBER;

SELECT ROUND(MEM_MILEAGE/12, 3) 마일리지 FROM MEMBER;

SELECT MOD(10,3) FROM DUAL;

SELECT FLOOR(1332.69), CEIL(1332.68) FROM DUAL;
SELECT  FLOOR(-1332.69), CEIL(-1332.69) FROM DUAL;

-- WIDTH_BUCKET([값],[MIN값],[MAX값],[구간 수])
SELECT WIDTH_BUCKET(55, 0, 100, 10) 어떤범위에속하는가 FROM DUAL;
SELECT MEM_ID, MEM_NAME, MEM_MILEAGE,
        WIDTH_BUCKET(MEM_MILEAGE, 9000, 500, 5) MILEAGE_GROUP
        FROM MEMBER ORDER BY MILEAGE_GROUP;
        
SELECT  ROUND(345.123 - 0.05, 1) AS "RESULT1" , 
        ROUND(345.123 - 0.5, 0)  AS "RESULT2", 
        ROUND(345.123 - 5, -1)   AS "RESULT3"  
        FROM DUAL; 

SELECT 10000 / 7 FROM DUAL;
SELECT FLOOR(10000 / 7 * 1000) / 1000 FROM DUAL;
SELECT FLOOR(10000 / 7 * 100) / 100 FROM DUAL;
SELECT FLOOR(10000 / 7 * 10) / 10 FROM DUAL;
SELECT FLOOR(10000 / 7 ) FROM DUAL;
SELECT FLOOR(10000 / 7 / 10) * 10 FROM DUAL;
SELECT FLOOR(10000 / 7 / 100) * 100 FROM DUAL;
SELECT FLOOR(10000 / 7 / 1000) * 10000 FROM DUAL;

SELECT SYSDATE 현재시간, SYSDATE - 1 "어제 이시간", SYSDATE+1 "내일 이시간"
        FROM DUAL;
        
SELECT SYSDATE 오늘날짜, LAST_DAY(SYSDATE) "이달 마지막 날짜",
        LAST_DAY(SYSDATE) - SYSDATE "이번달에 남은 날짜"
        FROM DUAL;











