
delete from empp;
delete from dept;

-- 문제용 테이블 CREATE

CREATE TABLE EMPP
(EMPNO      CHAR(4) NOT NULL ENABLE, 
	ENAME      VARCHAR2(20) NOT NULL ENABLE, 
	JOB        VARCHAR2(30) NOT NULL ENABLE, 
	MGR        VARCHAR2(4), 
	HIREDATE   DATE NOT NULL ENABLE, 
	SAL        NUMBER(10,0) NOT NULL ENABLE, 
	COMM       NUMBER, 
	DEPTNO     VARCHAR2(2) NOT NULL ENABLE,
CONSTRAINT XPK_EMP PRIMARY KEY (EMPNO) );

CREATE TABLE DEPT
(DEPTNO     CHAR(2) NOT NULL ENABLE,
	DNAME      VARCHAR2(20) NOT NULL ENABLE, 
	LOC        VARCHAR2(30) NOT NULL ENABLE,
CONSTRAINT XPK_DEPT PRIMARY KEY (DEPTNO) );

-- 사원관리
INSERT INTO EMPP(EMPNO,  ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7369', '장길동', '프로그래머', '7902', '2013/12/17', 600, 200 , '50');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7499', '고영우', '시장조사', '7698', '2021/02/20', 550, 300 , '20');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7521', '구기현', '영업사원', '7698', '2020/02/22', 250, 400 , '30');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7566', '김동혁', '관리자', '7839', '2012/04/02', 375,NULL, '40');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7654', '김민욱', '영업사원', '7698', '2018/09/28', 350, 700 , '30');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7698', '김민정', '관리자', '7839', '2014/05/01', 450,NULL, '40');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7782', '김지완', '관리자', '7839', '2022/02/20', 470, 600, '40');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7788', '박승우', '분석가', '7839', '2021/03/22', 300,NULL , '50');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7839', '박윤수', '대표이사', NULL, '2010/01/05', 900, 100, '40');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7844', '박정수', '영업사원', '7698', '2016/09/28',340,NULL, '30');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7876', '배문기', '회계업무', '7788', '2014/05/01', 420,NULL, '10');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7900', '변정민', '시장분석', '7698', '2012/04/02', 750,NULL, '20');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7902', '신국현', '분석가', '7566', '2019/09/28', 300,NULL, '50');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7934', '신현근', '프로그래머', '7782', '2018/01/23', 290,400, '50');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7999', '오대환', '회계업무', '7782',SYSDATE, 210,NULL, '10');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('8000', '정범진', '프로그래머', '7839',SYSDATE, 6500,NULL, '50');
INSERT INTO EMPP(EMPNO,	 ENAME,	JOB, MGR, HIREDATE, SAL,	COMM,	DEPTNO)
    VALUES('7997', '김민수', '프로그래머', '7839',SYSDATE, 6500,NULL, '30');

UPDATE EMPP SET DEPTNO='40' WHERE ENAME = '김민수';

SELECT * FROM EMPP ORDER BY EMPNO ASC;
SELECT TO_DATE(HIREDATE, 'YYMMDD') FROM EMPP;

-- 부서관리
INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES('10', '회계부', '서울');
INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES('20', '조사부', '세종');
INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES('30', '영업부', '서울');
INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES('40', '관리부', '대전');
INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES('50', '개발부', '대전');

UPDATE EMPP SET HIREDATE = TO_DATE('20'||TO_CHAR(hiredate), 'YYYY/MM/DD');


SELECT ENAME 사원명, DEPTNO 부서번호 
        FROM EMPP WHERE DEPTNO BETWEEN 20 AND 30 ORDER BY ENAME DESC;

SELECT ENAME 사원명, SAL 급여, DEPTNO 부서번호 
        FROM EMPP 
        WHERE SAL BETWEEN 200 AND 900 AND (DEPTNO = 20 OR DEPTNO = 30) ORDER BY ENAME ASC;
SELECT ENAME 사원명, SAL 급여, DEPTNO 부서번호 
        FROM EMPP 
        WHERE SAL BETWEEN 200 AND 900 AND DEPTNO IN (20,30) ORDER BY ENAME ASC;

SELECT ENAME 사원명, HIREDATE 입사일 FROM EMPP WHERE HIREDATE LIKE '12%';
SELECT ENAME 사원명, HIREDATE 입사일 FROM EMPP WHERE HIREDATE LIKE '___05%';

SELECT ENAME 사원명, JOB 담당업무 FROM EMPP WHERE MGR IS NULL;
SELECT ENAME 사원명, JOB 담당업무 FROM EMPP WHERE MGR IS NOT NULL;

SELECT ENAME 사원명, SAL 급여, COMM 커미션 FROM EMPP 
        WHERE COMM IS NOT NULL ORDER BY COMM DESC;

SELECT ENAME 사원명 FROM EMPP WHERE ENAME LIKE '__수%';
SELECT ENAME 사원명 FROM EMPP WHERE ENAME LIKE '_정%';

SELECT ENAME 사원명 FROM EMPP WHERE ENAME LIKE '%수%' AND ENAME LIKE '%박%';

SELECT ENAME 사원명, JOB 담당업무, SAL 급여 FROM EMPP WHERE NOT SAL IN(350, 550, 300);

SELECT ENAME 사원명, SAL 급여, COMM 커미션 FROM EMPP WHERE COMM>=400;
SELECT ENAME 사원명, SAL 급여, COMM 커미션 FROM EMPP 
        WHERE JOB IS NOT NULL AND COMM>=500;

SELECT ENAME 사원명, SUBSTR(HIREDATE, 1, 2) 입사년도, SUBSTR(HIREDATE,4,2) 입사달 
        FROM EMPP ORDER BY 입사년도 ASC, 입사달 ASC;

SELECT * FROM EMPP WHERE MOD(EMPNO,2)=0;
SELECT * FROM EMPP WHERE MOD(SUBSTR(HIREDATE,1,2),2)!=0;

SELECT TO_DATE(SYSDATE) - TO_DATE('2023-01-01','YYYY-MM-DD') "날짜" FROM DUAL;

SELECT SUBSTR(HIREDATE,1,2)YY,SUBSTR(HIREDATE,4,2)MON, SUBSTR(HIREDATE,7,2)DY FROM EMPP;
SELECT SUBSTR(HIREDATE,1,2)YY,SUBSTR(HIREDATE,4,2)MON, TO_CHAR(HIREDATE,'DAY') DY, 
        TO_DATE(SYSDATE) - TO_DATE(HIREDATE,'YY/MM/DD') || '일' 총근무일수 
        FROM EMPP ORDER BY YY ASC;

SELECT ENAME 사원명, NVL(MGR, 0) 사원번호 FROM EMPP ORDER BY 사원번호;
SELECT ENAME 사원명, NVL2(MGR, '상사있음', '상사없음') 사원번호 FROM EMPP ORDER BY 사원번호;

SELECT DECODE(10, 10, 'A', 9, 'B', 8, 'C', 'D') DECODE FROM DUAL;
SELECT ENAME 사원명, SAL 급여,
        DECODE(JOB, '분석가', SAL+200, 
                         '프로그래머', SAL+150, 
                         '영업사원', SAL+130, 
                         '관리자', SAL+110, SAL) 인상된급여
        FROM EMPP ORDER BY JOB DESC;

SELECT MAX(SAL) 최고액, MIN(SAL)최저액, SUM(SAL)총액, ROUND(AVG(SAL),3)평균
        FROM EMPP;
SELECT JOB, MAX(SAL) 최고액, MIN(SAL)최저액, SUM(SAL)총액, ROUND(AVG(SAL))평균
        FROM EMPP GROUP BY JOB ORDER BY 평균 DESC;












